In [1]:
%matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import numpy as np
import pandas as pd

In [3]:
import datetime as dt
from datetime import timedelta
from flask import Flask, jsonify

In [4]:
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [5]:
engine = create_engine("sqlite:///bellybutton.sqlite")
connection = engine.connect()

In [6]:
# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

In [7]:
Base.classes.keys()

['sample_metadata', 'samples']

In [8]:
Samples_Metadata = Base.classes.sample_metadata
Samples = Base.classes.samples

In [9]:
session = Session(engine)

In [45]:
stmt = session.query(Samples).statement
df = pd.read_sql_query(stmt, session.bind)

In [49]:
df.head()
sample = 940

In [50]:
sample_data = df.loc[df[f'{sample}'] > 1, ["otu_id", "otu_label", f'{sample}']]
sample_data.head()

     otu_id otu_label  940
40       41  Bacteria   71
120     121  Bacteria    2
158     159  Bacteria    2
164     165  Bacteria   12
169     170  Bacteria    2

In [51]:
sample_data.sort_values(by=[f'{sample}'], ascending=False, inplace=True)
sample_data

      otu_id                                          otu_label  940
1166    1167  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...  163
2858    2859  Bacteria;Firmicutes;Clostridia;Clostridiales;I...  126
481      482                                           Bacteria  113
2263    2264  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   78
40        41                                           Bacteria   71
1188    1189  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...   51
351      352                                           Bacteria   50
188      189                                           Bacteria   47
2317    2318  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   40
1976    1977       Bacteria;Firmicutes;Clostridia;Clostridiales   40
3449    3450  Bacteria;Proteobacteria;Epsilonproteobacteria;...   37
873      874  Bacteria;Actinobacteria;Actinobacteria;Actinom...   36
1958    1959                     Bacteria;Firmicutes;Clostridia   30
2190    2191  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   28
1949    1950                     Bacteria;Firmicutes;Clostridia   25
2076    2077       Bacteria;Firmicutes;Clostridia;Clostridiales   23
2274    2275  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   22
943      944  Bacteria;Actinobacteria;Actinobacteria;Actinom...   19
2183    2184  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   19
2243    2244  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   14
2023    2024       Bacteria;Firmicutes;Clostridia;Clostridiales   13
2418    2419  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   13
2810    2811  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   13
164      165                                           Bacteria   12
2781    2782  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   12
2246    2247  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   11
2010    2011       Bacteria;Firmicutes;Clostridia;Clostridiales   11
2395    2396  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   11
829      830  Bacteria;Actinobacteria;Actinobacteria;Actinom...   10
2963    2964  Bacteria;Firmicutes;Clostridia;Clostridiales;V...   10
...      ...                                                ...  ...
2474    2475  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2490    2491  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2290    2291  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
158      159                                           Bacteria    2
2570    2571  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2349    2350  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2341    2342  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2545    2546  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
724      725  Bacteria;Actinobacteria;Actinobacteria;Actinom...    2
169      170                                           Bacteria    2
1504    1505                                Bacteria;Firmicutes    2
512      513                                           Bacteria    2
258      259                                           Bacteria    2
1168    1169  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...    2
257      258                                           Bacteria    2
1231    1232  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...    2
1496    1497                                Bacteria;Firmicutes    2
1497    1498                                Bacteria;Firmicutes    2
1502    1503                                Bacteria;Firmicutes    2
411      412                                           Bacteria    2
2234    2235  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
1959    1960                     Bacteria;Firmicutes;Clostridia    2
1967    1968                     Bacteria;Firmicutes;Clostridia    2
120      121                                           Bacteria    2
2064    2065       Bacteria;Firmicutes;Clostridia;Clostridiales    2
339      340                                           Bacteria    2
2109    2110       Bacteria;Firmicutes;Clostridia;Clostridiales    2
2187    2188  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
356      357                                           Bacteria    2
341      342                                           Bacteria    2

[80 rows x 3 columns]

In [54]:
data = {
        "otu_ids": sample_data.otu_id.values.tolist(),
        "sample_values": sample_data[sample].values.tolist(),
        "otu_labels": sample_data.otu_label.tolist()
    }
data

KeyError: 940

KeyError: 'sample'

In [145]:
#df.loc[(df.iloc[3:155].sum(axis=1) != 0)]
#no_zero = df.loc[(df.iloc[:,2:len(df.columns)].sum(axis=1) != 0)]

In [146]:
#(no_zero.iloc[:,2:len(no_zero.columns)]).sum(axis=1).sort_values(ascending=False).head()

In [147]:
pie_df_i = pd.melt(df, id_vars =['otu_id','otu_label'],var_name='sample').groupby(['otu_id','otu_label']).sum().reset_index().sort_values(by=['value'],ascending=False).head(10)
pie_df_i

      otu_id                                          otu_label    value
1794    1795  Bacteria;Firmicutes;Bacilli;Bacillales;Staphyl...  18096.0
921      922  Bacteria;Actinobacteria;Actinobacteria;Actinom...  10078.0
943      944  Bacteria;Actinobacteria;Actinobacteria;Actinom...   5876.0
2418    2419  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   4295.0
1166    1167  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...   4244.0
2858    2859  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   4017.0
2538    2539  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   3875.0
2721    2722  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   3012.0
481      482                                           Bacteria   2160.0
727      728  Bacteria;Actinobacteria;Actinobacteria;Actinom...   2049.0

In [148]:
pie_df_i['perc']= round(pie_df_i['value']/pie_df_i['value'].sum()*100,2)
pie_df_i

,otu_id,otu_label,value,perc
1794,1795,Bacteria;Firmicutes;Bacilli;Bacillales;Staphyl...,18096.0,31.36
921,922,Bacteria;Actinobacteria;Actinobacteria;Actinom...,10078.0,17.47
943,944,Bacteria;Actinobacteria;Actinobacteria;Actinom...,5876.0,10.18
2418,2419,Bacteria;Firmicutes;Clostridia;Clostridiales;I...,4295.0,7.44
1166,1167,Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...,4244.0,7.36
2858,2859,Bacteria;Firmicutes;Clostridia;Clostridiales;I...,4017.0,6.96
2538,2539,Bacteria;Firmicutes;Clostridia;Clostridiales;I...,3875.0,6.72
2721,2722,Bacteria;Firmicutes;Clostridia;Clostridiales;I...,3012.0,5.22
481,482,Bacteria,2160.0,3.74
727,728,Bacteria;Actinobacteria;Actinobacteria;Actinom...,2049.0,3.55

In [153]:
otu_ids = pie_df_i['otu_id'].tolist()
sample_values = pie_df_i['perc'].tolist()
otu_labels = pie_df_i['otu_label'].tolist()